#!/bin/sh
#
# This script is run by pppd after the connection has ended.
#
# 解析变量
DEL_VPN_SERVE=$(echo "$IPPARAM" | awk -F: '{print $1}')
DEL_GW_LAN_IP=$(echo "$IPPARAM" | awk -F: '{print $2}')
DEL_NET_INTERFACE=$(echo "$IPPARAM" | awk -F: '{print $3}')

# 删除路由
ip route del $DEL_VPN_SERVE via $DEL_GW_LAN_IP dev $DEL_NET_INTERFACE
ip route del 128.0.0.0/1 via $REMOTE_IP dev $INTERFACE
ip route del 0.0.0.0/1 via $REMOTE_IP dev $INTERFACE
