#!/bin/sh
#
# This script is run by pppd after the connection has ended.
# 这里的断开不是指 echo "d myvpn ..." 这样的手动断开，而是意外中断连接
# 重命名参数为有意义的变量名
INTERFACE="$1"	          # 对应 interface-name
# PPP_TTY="$2"            # 对应 tty-device
# PPP_SPEED="$3"          # 对应 speed
# PPP_LOCAL_IP="$4"       # 对应 local-IP-address
REMOTE_IP="$5"      # 对应 remote-IP-address
IPPARAM="$6"        	  # 对应 ipparam

# 解析变量
DEL_VPN_SERVE=$(echo "$IPPARAM" | awk -F: '{print $1}')
DEL_GW_LAN_IP=$(echo "$IPPARAM" | awk -F: '{print $2}')
DEL_NET_INTERFACE=$(echo "$IPPARAM" | awk -F: '{print $3}')

# 删除路由
ip route del 128.0.0.0/1 via $REMOTE_IP dev $INTERFACE
ip route del 0.0.0.0/1 via $REMOTE_IP dev $INTERFACE
ip route del $DEL_VPN_SERVE via $DEL_GW_LAN_IP dev $DEL_NET_INTERFACE
